config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [ :new, :create, :index ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :category, presence: true
  validates :category, :inclusion => { :in => ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, :inclusion => { :in => 0..5 }
  validates :rating, numericality: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurants_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.delete
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phonenumber)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def controller
  end

  def index
    @reviews = Review.where(restaurant_id: Restaurant.find(params[:restaurant_id]))
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    # we need `restaurant_id` to asssociate review with corresponding restaurant
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <!-- [...] -->
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">

  <h1>Restaurants#index</h1>
  <p>Find me in app/views/restaurants/index.html.erb</p>

  <ul>
    <% @restaurants.each do |restaurant| %>
     <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
    <% end %>
  </ul>

  <%= link_to 'Add Restaurant', new_restaurant_path, :class => 'btn btn-primary' %>
</div>

app/views/restaurants/new.html.erb
<div class="container">

  <h1>Restaurants#new</h1>
  <p>Find me in app/views/restaurants/new.html.erb</p>

  <%= simple_form_for @restaurant do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :category %>
    <%= f.input :phone_number %>
    <%= f.submit "add a restaurant", class: "btn btn-primary" %>
  <% end %>

</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="card">
    <div class="card-header">
      <%= @restaurant.name %>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= @restaurant.category %></h5>
      <p class="card-text"><%= @restaurant.address %></p>
      <%= link_to 'Write a Review', new_restaurant_review_path(@restaurant) , :class => 'btn btn-primary' %>
      <%= link_to 'All Reviews', restaurant_reviews_path(@restaurant), :class => 'btn btn-primary' %>
      <%= link_to 'Delete', restaurant_path(@restaurant), :class => 'btn btn-danger', method: :delete %>
    </div>
  </div>
</div>

app/views/reviews/controller.html.erb
<h1>Reviews#controller</h1>
<p>Find me in app/views/reviews/controller.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>
<ul>
  <% @reviews.each do |review| %>
    <li><%= review.content %></li>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

<div class="container">

  <h1>Restaurants#review</h1>
  <p>Find me in app/views/reviews/create.html.erb</p>

  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit "add a restaurant", class: "btn btn-primary" %>
  <% end %>

</div>